### ISSUE TITLE
Mistake in ESP8266 D1 mini pinout diagram

### ISSUE THREAD

**Issue by QubeCode** [Aircoookie/WLED-Docs#142]
In the [Top 5 mistakes page](https://kno.wled.ge/basics/top5_mistakes/) is a pinout diagram for the ESP8266 D1 mini (2nd image).
In there, pin `D4` is labled `GPIO 3`, just like `RX` pin.
To my knowledge, it is actually `GPIO 2`.
@wled-faq

**Comment by blazoncek** [comment]
Please tag @wled-faq
