### ISSUE TITLE
(feature request) guide for ethernet

### ISSUE THREAD

**Issue by softhack007** [Aircoookie/WLED-Docs#160]
Would be nice if some kind soul who has ethernet up and running with WLED would make a short guide for ethernet setup.
* list of boards supported (you can take that directly from the source code)
* how to switch to ethernet, after first connecting to WLED-AP
* static IP, or dynamic IP
* notes / fallacies / pitfalls, 
* limitations and caveats for specific boards (if possible)
* GPIO limitations (some pins are not usable)

**Comment by softhack007** [comment]
List of boards according to [source code](https://github.com/Aircoookie/WLED/blob/5eadbe7ecd21fedc60d1fec7066c382014e9b968/wled00/network.cpp#L19):

* ABC! WLED V43 & compatible
* ESP32-POE
* ESP32Deux
* KIT-VE
* QuinLED-Dig-Octa & T-ETH-POE
* QuinLED-ESP32
* Serg74-ETH32
* TwilightLord-ESP32
* WESP32
* WT32-ETH01

**Comment by blazoncek** [comment]
@scottrbailey or @dosipod or @wled-faq could you help, please?

**Comment by dosipod** [comment]
I do not own  Ethernet board so could not

**Comment by wled-faq** [comment]
I could add Info, but I only have my boards, therefore some questions:
   - "how to switch to ethernet, after first connecting to WLED-AP" --> Is there any issues/complications? I think I just select etehrnet Type and plug LAN cable, then communictae via LAN IP
  - "static IP, or dynamic IP" --> General advatages/drawbacks or there is some special to WLED?
  - "notes / fallacies / pitfalls" --> For example?

**Comment by rorosaurus** [comment]
Current docs do show what pins aren't available and what controllers are supported. There's also an explanation about how to select your board from the settings page. I think this is resolved?

**Comment by blazoncek** [comment]
@softhack007 do you agree?

**Comment by softhack007** [comment]
@blazoncek ok for me to close this ticket now. Thanks @wled-faq for improving the docs 🥇
