### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by SlimePuppyRR** [Aircoookie/WLED-Docs#168]
I found a typo in the docs (https://kno.wled.ge/advanced/remote-access-ifttt/)

3. Port Forwarding
[...]
 Use a 5 digit port for better **securuty**.

**Comment by blazoncek** [comment]
Please fork, update and make a PR.

**Comment by SlimePuppyRR** [comment]
I'm new to GitHub and don't know all the terms;
What does PR mean?

**Comment by blazoncek** [comment]
PR = Pull request
Pull request is a means of including your changes into official repository.

https://github.com/Aircoookie/WLED/wiki/How-to-properly-submit-a-PR

**Comment by WoodyLetsCode** [comment]
This issue can be closed. This typo no longer exists.
