### ISSUE TITLE
74AHCT125 drawing errors

### ISSUE THREAD

**Issue by gwugg** [Aircoookie/WLED-Docs#175]
https://kno.wled.ge/basics/compatible-hardware/#levelshifters  drawings for 74AHCT125 show OE pins connected to +5V but I think they are active low and should be connected directly to ground only.

**Comment by blazoncek** [comment]
The drawings (schematics) are correct. Please study them thoroughly.

**Comment by gwugg** [comment]
https://www.ti.com/lit/ds/symlink/sn74ahct125.pdf data sheet shows signal OE is active low.  "When OE is low, the respective gate passes the data from the A input to its Y output."

**Comment by blazoncek** [comment]
Exactly. And now check schematics again.

**Comment by gwugg** [comment]
Like a Labrador Retriever dog, I ran to an unused pin and started barking!  Thanks for your patience and sorry for the noise.  Woof.
