### ISSUE TITLE
"What Binary" doesn't line up with the latest BIN file releases

### ISSUE THREAD

**Issue by chunkysteveo** [Aircoookie/WLED-Docs#27]
Howdy AirCookie!

Great work as always. Just a note/correction that the documents for https://kno.wled.ge/basics/install-binary/#what-binary-should-i-use don't match the available binaries of the latest release - more specifically for users of 1Mb ESP8266 devices, there's new ones for 1Mb, 2Mb etc, but the documents still talk about ESP01 bin file.

Steve

**Comment by eibanez** [comment]
I took a look and this does not look like a problem. Am I missing something?

This is the list of assets under 0.13.0-b5:
![image](https://user-images.githubusercontent.com/438494/144283530-e5b2c1c9-1b1f-4740-85dc-376621743adf.png)

This is the list in the docs:
![image](https://user-images.githubusercontent.com/438494/144283621-f905ca17-41d5-45da-bad6-aaa8a0209227.png)

**Comment by chunkysteveo** [comment]
The new releases look more in line. The 0.12 release didn't match up for the ESP01 1Mb 2Mb when I raised it. Happy to close off 👍🏻
