### ISSUE TITLE
Improve "Install using ESP GUI"

### ISSUE THREAD

**Issue by CWempe** [Aircoookie/WLED-Docs#4]
I just discovered the new wiki.

Here are a few notes:

![image](https://user-images.githubusercontent.com/1270359/127918555-da6846fd-14db-4852-ad23-26d378bd7cb6.png)

1. The link does not work (error 404)
2. Why is this link not clickable?
3. At first it was unclear I had to search with google.  
  Searching with these keywords on the espressif site did not help. 😄 
  But the link in (2) worked when I copied it correctly. So there was no need for using search in the first place.

**Comment by CWempe** [comment]
I think the tool also got updated (v3.8.8).

The first window to pop up looks like this:

![image](https://user-images.githubusercontent.com/1270359/127919653-2914645a-0e59-4483-b158-2d2a077ad282.png)

![image](https://user-images.githubusercontent.com/1270359/127919785-25733375-5854-49ee-835b-c0943d71bd44.png)



Another issue:

First time i followed the instructions I got this:

![image](https://user-images.githubusercontent.com/1270359/127920444-2f0fae3f-f2be-4d65-8ce9-a5100f3d5c47.png)

I think this is because the guide says 
> Now just click on the Developer Mode and `ESP8266` [..]

But I tried to upload to an ESP32.
It worked when I selected `ESP32` in the first window.
So the guide should tell the user to select the correct ChipType.

**Comment by Aircoookie** [comment]
Hi and thank you!
I have now fixed the page according to the feedback from your first post :)

I am however considering removing that page as the installation methods described in https://kno.wled.ge/basics/install-binary/ are a lot easier. Do you think using the Download Tool has some benefit I am overlooking?

**Comment by CWempe** [comment]
> Do you think using the Download Tool has some benefit I am overlooking?

I am not sure I am qualified to answer this. 😄 

But in the end I actually used `esptool.py`, too. 😉 

I would also suggest to explain the `with_booloader` file.

![image](https://user-images.githubusercontent.com/1270359/128641786-d7ea2ad8-eaff-4e81-b4b2-1f1e8d1a4bf5.png)

This might be usefull for users (like me).
At least it sound like you could skip the step of flashing `esp32_bootloader_v2.bin` this way.
